[package]
name = "omavim"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A dead-simple writing app with Vim motions"

[dependencies]
ashpd = { version = "0.13", default-features = false, features = ["tokio", "file_chooser", "settings", "print"] }
futures = "0.3"
iced = { version = "0.14", features = ["advanced", "tokio"] }
krilla = { version = "0.8", default-features = false, features = ["simple-text"] }
omavim-syntax = { path = "../omavim-syntax" }
omavim-vim = { path = "../omavim-vim" }
ropey = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["fs", "rt"] }
toml = "0.9"
