[package]
name = "omavim"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A dead-simple writing app with Vim motions"

[dependencies]
ashpd = { version = "0.13", default-features = false, features = ["tokio", "file_chooser", "settings"] }
futures = "0.3"
iced = { version = "0.14", features = ["advanced", "tokio"] }
omavim-vim = { version = "0.1.0", path = "../omavim-vim" }
ropey = "1"
tokio = { version = "1", features = ["fs", "rt"] }
